  version: '3.8'

  services:
    frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      environment:
        - API_URL=http://0.0.0.0:8000/api/
        
    backend:
      build: ./backend
      ports:
        - "8000:8000"
      environment:
        - DB_ENGINE=django.db.backends.sqlite3
        - DB_NAME=/data/db.sqlite3
      volumes:
        - ./backend:/app
        - backend_data:/data

  volumes:
    backend_data:
